// User Roles
exports.ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  STATE_ADMIN: 'STATE_ADMIN',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  BLOCK_MANAGER: 'BLOCK_MANAGER',
  WARD_MANAGER: 'WARD_MANAGER',
  BOOTH_WORKER: 'BOOTH_WORKER',
  VOLUNTEER: 'VOLUNTEER'
};

// Area Types
exports.AREA_TYPES = {
  STATE: 'STATE',
  DISTRICT: 'DISTRICT',
  BLOCK: 'BLOCK',
  VILLAGE: 'VILLAGE',
  WARD: 'WARD',
  BOOTH: 'BOOTH'
};

// Task Status
exports.TASK_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Voter Engagement Levels
exports.ENGAGEMENT_LEVELS = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  NONE: 'NONE'
};

// Support Levels
exports.SUPPORT_LEVELS = {
  STRONG_SUPPORTER: 'STRONG_SUPPORTER',
  SUPPORTER: 'SUPPORTER',
  NEUTRAL: 'NEUTRAL',
  OPPONENT: 'OPPONENT',
  UNKNOWN: 'UNKNOWN'
};
